# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch ( should add the sprint branch to triggers every sprint )
  push:
    branches: [main, develop, develop_live, develop_68]
  pull_request:
    branches: [main, develop, develop_live, develop_68]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: yarn

      # Runs a single command using the runners shell
      - name: Eslint fix and check
        run: yarn eslint:fix

      # Runs a single command using the runners shell
      - name: Create Spring Configs Dev file for tests running
        run: ./prepare-tests.sh

      - name: Run tests
        run: yarn test --watchAll=false
